import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Polski Alert Smogowy | App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="relative w-full min-h-screen overflow-hidden">
      {children}
    </main>
  );
}
