import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { authOptions } from "@/utils/authenticate";

export const metadata: Metadata = {
  title: "Polski Alert Smogowy | ADmin",
  description: "Generated by create next app",
};

export default async function AdminLayout({ children }: { children: React.ReactNode }) {
  return <main className="relative w-full min-h-screen overflow-hidden">{children}</main>;
}
